# Generated by Django 6.0 on 2025-12-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_todo_completed_todo_date_todo_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='details',
            field=models.TextField(default='No details'),
        ),
    ]
